/*
	This simple extension of the java.awt.Frame class
	contains all the elements necessary to act as the
	main window of an application.
 */
// package org.csac.bits;

import java.awt.*;
import java.awt.datatransfer.*;
import org.csac.bits.*;
import org.csac.bits.EntityType;
import org.csac.bits.RBitmap;
import org.csac.bits.R2Bitmap;
import org.csac.bits.Property;
import org.csac.bits.Relation;

public class Frame2 extends Frame implements ClipboardOwner
{
	java.awt.datatransfer.Clipboard cb;
	EntityType et;
	public Frame2()
	{
		// This code is automatically generated by Visual Cafe when you addButton
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		
		//{{INIT_CONTROLS
		setLayout(null);
		setVisible(false);
		setSize(585,490);
		nameField = new java.awt.TextField();
		nameField.setBounds(105,408,122,40);
		add(nameField);
		addButton = new java.awt.Button();
		addButton.setLabel("Add String");
		addButton.setBounds(262,420,71,22);
		add(addButton);
		openFileDialog1 = new java.awt.FileDialog(this);
		openFileDialog1.setMode(FileDialog.LOAD);
		openFileDialog1.setTitle("Open");
		//$$ openFileDialog1.move(50,464);
		textArea1 = new java.awt.TextArea();
		textArea1.setBounds(45,33,506,355);
		add(textArea1);
		dumpButton = new java.awt.Button();
		dumpButton.setLabel("Dump Strings");
		dumpButton.setBounds(432,420,89,21);
		add(dumpButton);
		findButton = new java.awt.Button();
		findButton.setLabel("Find String");
		findButton.setBounds(346,420,71,22);
		add(findButton);
		setTitle("Bitmaps rule");
		//}}
		
		//{{INIT_MENUS
		mainMenuBar = new java.awt.MenuBar();
		menu1 = new java.awt.Menu("File");
		miNew = new java.awt.MenuItem("New");
		miNew.setShortcut(new MenuShortcut(java.awt.event.KeyEvent.VK_N,false));
		menu1.add(miNew);
		miOpen = new java.awt.MenuItem("Open...");
		miOpen.setShortcut(new MenuShortcut(java.awt.event.KeyEvent.VK_O,false));
		menu1.add(miOpen);
		miSave = new java.awt.MenuItem("Save");
		miSave.setShortcut(new MenuShortcut(java.awt.event.KeyEvent.VK_S,false));
		menu1.add(miSave);
		miSaveAs = new java.awt.MenuItem("Save As...");
		menu1.add(miSaveAs);
		menu1.addSeparator();
		miExit = new java.awt.MenuItem("Exit");
		menu1.add(miExit);
		mainMenuBar.add(menu1);
		menu2 = new java.awt.Menu("Edit");
		miCut = new java.awt.MenuItem("Cut");
		miCut.setShortcut(new MenuShortcut(java.awt.event.KeyEvent.VK_X,false));
		menu2.add(miCut);
		miCopy = new java.awt.MenuItem("Copy");
		miCopy.setShortcut(new MenuShortcut(java.awt.event.KeyEvent.VK_C,false));
		menu2.add(miCopy);
		miPaste = new java.awt.MenuItem("Paste");
		miPaste.setShortcut(new MenuShortcut(java.awt.event.KeyEvent.VK_V,false));
		menu2.add(miPaste);
		mainMenuBar.add(menu2);
		menu3 = new java.awt.Menu("Help");
		mainMenuBar.setHelpMenu(menu3);
		miAbout = new java.awt.MenuItem("About..");
		menu3.add(miAbout);
		mainMenuBar.add(menu3);
		setMenuBar(mainMenuBar);
		//$$ mainMenuBar.move(14,461);
		//}}
		
		//{{REGISTER_LISTENERS
		SymWindow aSymWindow = new SymWindow();
		this.addWindowListener(aSymWindow);
		SymAction lSymAction = new SymAction();
		miOpen.addActionListener(lSymAction);
		miAbout.addActionListener(lSymAction);
		miExit.addActionListener(lSymAction);
		SymMouse aSymMouse = new SymMouse();
		this.addMouseListener(aSymMouse);
		addButton.addActionListener(lSymAction);
		findButton.addActionListener(lSymAction);
		dumpButton.addActionListener(lSymAction);
		//}}
		et = new org.csac.bits.EntityType("Fischers");
		et.addName("michael");
		et.addName("Jimmi");
		et.addName("Nancy");
		et.addName("Michael");
		
	}
	
	public Frame2(String title)
	{
		this();
		setTitle(title);
	}
	
    /**
     * Shows or hides the component depending on the boolean flag b.
     * @param b  if true, show the component; otherwise, hide the component.
     * @see java.awt.Component#isVisible
     */
    public void setVisible(boolean b)
	{
		if(b)
		{
			setLocation(50, 50);
		}	
		super.setVisible(b);
	}
	
	static public void main(String args[])
	{
		(new Frame2()).setVisible(true);
	}
	
	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension d = getSize();
		
		super.addNotify();
	
		if (fComponentsAdjusted)
			return;
	
		// Adjust components according to the insets
		setSize(insets().left + insets().right + d.width, insets().top + insets().bottom + d.height);
		Component components[] = getComponents();
		for (int i = 0; i < components.length; i++)
		{
			Point p = components[i].getLocation();
			p.translate(insets().left, insets().top);
			components[i].setLocation(p);
		}
		fComponentsAdjusted = true;
	}
	
	// Used for addNotify check.
	boolean fComponentsAdjusted = false;
	
	//{{DECLARE_CONTROLS
	java.awt.TextField nameField;
	java.awt.Button addButton;
	java.awt.FileDialog openFileDialog1;
	java.awt.TextArea textArea1;
	java.awt.Button dumpButton;
	java.awt.Button findButton;
	//}}
	
	//{{DECLARE_MENUS
	java.awt.MenuBar mainMenuBar;
	java.awt.Menu menu1;
	java.awt.MenuItem miNew;
	java.awt.MenuItem miOpen;
	java.awt.MenuItem miSave;
	java.awt.MenuItem miSaveAs;
	java.awt.MenuItem miExit;
	java.awt.Menu menu2;
	java.awt.MenuItem miCut;
	java.awt.MenuItem miCopy;
	java.awt.MenuItem miPaste;
	java.awt.Menu menu3;
	java.awt.MenuItem miAbout;
	//}}
	
	class SymWindow extends java.awt.event.WindowAdapter
	{
		public void windowClosing(java.awt.event.WindowEvent event)
		{
			Object object = event.getSource();
			if (object == Frame2.this)
				Frame2_WindowClosing(event);
		}
	}
	
	void Frame2_WindowClosing(java.awt.event.WindowEvent event)
	{
		setVisible(false);	// hide the Frame
		dispose();			// free the system resources
		System.exit(0);		// close the application
	}
	
	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == miOpen)
				miOpen_Action(event);
			else if (object == miAbout)
				miAbout_Action(event);
			else if (object == miExit)
				miExit_Action(event);
			else if (object == addButton)
				addButton_ActionPerformed(event);
			else if (object == findButton)
				findButton_ActionPerformed(event);
			else if (object == dumpButton)
				dumpButton_ActionPerformed(event);
		}
	}
	
	void miAbout_Action(java.awt.event.ActionEvent event)
	{
		//{{CONNECTION
		// Action from About Create and show as modal
		(new AboutDialog(this, true)).setVisible(true);
		//}}
	}
	
	void miExit_Action(java.awt.event.ActionEvent event)
	{
		//{{CONNECTION
		// Action from Exit Create and show as modal
		(new QuitDialog(this, true)).setVisible(true);
		//}}
	}
	
	void miOpen_Action(java.awt.event.ActionEvent event)
	{
		//{{CONNECTION
		// Action from Open... Show the OpenFileDialog
		openFileDialog1.setVisible(true);
		
		//Work around MRJ bug
		openFileDialog1.setVisible(false);
		//}}
	}

	class SymMouse extends java.awt.event.MouseAdapter
	{
		public void mouseReleased(java.awt.event.MouseEvent event)
		{
			Object object = event.getSource();
			if (object == Frame2.this)
				Frame2_MouseReleased(event);
		}
	}

	

	void Frame2_MouseReleased(java.awt.event.MouseEvent event)
	{
		Property jj = new Property("jj","Fischers");
		Property jk = new Property("jk","Fischers");
		Property jl = new Property("jl","Fischers");
		// to do: code goes here.
		System.out.println("Here");
		//{{CONNECTION
		// Append string in TextArea Get Frame2 title
	/*	for (int i = 0;i<256;i++) {
			int k = i;
			int n = 0;
			for (int j = 0;j<8;j++) {
				if ((k & 1) == 1) n++;
				k >>= 1;
			}
			if (i % 16 == 0) textArea1.append("\n");
			textArea1.append(n+", ");
		}*/
		//cb = new Clipboard("more");
		//cb.setContents(new StringSelection(textArea1.getText()),this);
	/*	textArea1.append(jj.bits.countBits((byte) 0xfe)+"\n");
		textArea1.append(jj.bits.countBits((short) 0x100)+"\n");
		textArea1.append(jj.bits.countBits(0xffff)+"\n");
		textArea1.append(jj.bits.countBits(0xfffff)+"\n");
		textArea1.append(jj.bits.countBits(0xfffffe)+"\n");
		textArea1.append(jj.bits.countBits(0xfffffff)+"\n");
		textArea1.append(jj.bits.countBits((long) 0xffffffffffeL)+"\n");*/
		
		jj.setBit("michael",true);
		jj.setBit("Jimmi",true);
		jj.setBit("Nancy",true);
		jj.setBit("Michael",true);
		jj.setBit("Mike",true);
		jj.setBit("Frost",true);
		jj.setBit("Mist",true);
		jj.setBit(4031);
		jj.setBit(4032);
		jj.setBit("Wenonah",true);
		
		textArea1.append(jj.toString()+"\n\n");
		EntityType fi = EntityType.getEntityType("Fischers");
		textArea1.append("Fischers type= "+fi.listNames()+"\n\n");
		
		String [] a = {"a","b","c","d","e","f","whatever"};
		jk.setBits(a);
		textArea1.append("jk="+jk.toString()+"\n");
		String [] b = {"this","that","whatever","whenever","d","e","f"};
		jl.setBits(b);	
		textArea1.append("jl="+jl.toString()+"\n\n");
		//jl.and(jk);
		//textArea1.append("jk="+jl.toString()+"\n");
		jk.not();
		textArea1.append("Not jk="+jk.toString()+"\n");
		// jk.not();
		// textArea1.append("Not jk="+jk.toString()+"\n");
		jk.xor(jl);
		textArea1.append("xor jk:jl="+jk.toString()+"\n\n");
		jk.not();
		textArea1.append("not jk:="+jk.toString()+"\n\n");
		jk.and(jl);
		textArea1.append("and jk:jl="+jk.toString()+"\n\n");
		
		fi = EntityType.getEntityType("Fischers");
		textArea1.append("Fischers type= "+fi.listNames()+"\n\n");

		Relation k = new Relation("k","Bits1","Bits2");
		Relation l = new Relation("l","Bits1","Bits2");
		long[] s = {122,999,222,111,333,444,555,888,777,666};
		long[] t = {1122,999,222,111,333,444,555,888,777,666};
		long[] u = {212,999,222,111,333,444,555,888,777,666,41};
		long[] v = {900,999,222,111,333,444,555,888,777,666,41};
	
		long[] s1 = {122,999,221,111,333,444,555,888,777,665};
		long[] t1 = {1122,999,222,111,333,443,555,889,777,666};
		long[] u1 = {213,998,220,111,333,444,555,889,776,666,40};
		long[] v1 = {900,998,220,111,333,444,555,889,776,666,40};

RBitmap z1 = new RBitmap(0);
RBitmap z2 = new RBitmap(0);
z1.setBits(v);
z2.setBits(v1);
z1.xor(z2);
textArea1.append("z1 xor z2  "+z1.toString()+"\n");

		k.bmap.setBits(u);
		k.bmap.setBits(v);
		k.bmap.setBits(s);
		k.bmap.setBits(t);

		l.bmap.setBits(t1);
		l.bmap.setBits(u1);
		l.bmap.setBits(s1);
		l.bmap.setBits(v1);
//		long[][] q = {{9999,9998},{8888,8887},{7777,7776}};
//		k.setBits(q);

		textArea1.append("Bitmap k\n");
		textArea1.append(k.toString()+"\n");
		
		textArea1.append("Bitmap l\n");
		textArea1.append(l.toString()+"\n");
		
		Relation m = new Relation("m","Bits1","Bits2");

		k.and(l,m);

		textArea1.append("Bitmap and\n");
		textArea1.append(m.toString()+"\n");

	//	k.xor(l,m);

	//	textArea1.append("Bitmap xor\n");
	//	textArea1.append(m.toString()+"\n");
		m = new Relation("m-new","Bits1","Bits2");
		k.xor(l,m);

		textArea1.append("Bitmap xor\n");
		textArea1.append(m.toString()+"\n");
		
		m.reverse(m);

		textArea1.append("Bitmap m reverse\n");
		textArea1.append(m.toString()+"\n");
	
	//}}
	}
	
	public void lostOwnership(Clipboard b, Transferable c) {
		
	}
	

	void addButton_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		//{{CONNECTION
		// Set Frame2 title Get the contents of the TextField
		textArea1.appendText(et.addName(nameField.getText())+"\n");
		//}}
	}

	void findButton_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		//{{CONNECTION
		// Set Frame2 title Get the selected text
		textArea1.appendText(et.findName(nameField.getText())+"\n");
		//}}
	}

	void dumpButton_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
			 
		//{{CONNECTION
		// Set Frame2 title Get the selected text
		int sz = et.getSize();
		for (int i=0;i<sz;i++) {
			textArea1.appendText(i+": "+et.getName(i)+"\n");
		}
		System.out.println("Here 2");
		// Frame2_MouseReleased(null);
		//}}
	}
}

